"""increasing the length of booking status

Revision ID: 12365128d21c
Revises: fbc50b094970
Create Date: 2026-06-25 14:02:38.943311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12365128d21c'
down_revision = 'fbc50b094970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
