"""adding last_login to User table

Revision ID: b169ee001fb5
Revises: 12365128d21c
Create Date: 2026-06-25 14:28:02.414367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b169ee001fb5'
down_revision = '12365128d21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_suspended')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
