"""add verification document to business

Revision ID: bff36bb57d1a
Revises: e9a91ba5951a
Create Date: 2026-07-14 23:26:47.521692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff36bb57d1a'
down_revision = 'e9a91ba5951a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_document', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('verification_document')

    # ### end Alembic commands ###
